In [1]:
import pandas as pd

In [4]:
pd.read_excel("data/wfh_boys_2-to-5-years_zscores.xlsx")

,Height,L,M,S,SD3neg,SD2neg,SD1neg,SD0,SD1,SD2,SD3
0,65.0,-0.3521,7.4327,0.08217,5.9,6.3,6.9,7.4,8.1,8.8,9.6
1,65.5,-0.3521,7.5504,0.08214,6.0,6.4,7.0,7.6,8.2,8.9,9.8
2,66.0,-0.3521,7.6673,0.08212,6.1,6.5,7.1,7.7,8.3,9.1,9.9
3,66.5,-0.3521,7.7834,0.08212,6.1,6.6,7.2,7.8,8.5,9.2,10.1
4,67.0,-0.3521,7.8986,0.08213,6.2,6.7,7.3,7.9,8.6,9.4,10.2
...,...,...,...,...,...,...,...,...,...,...,...
106,118.0,-0.3521,21.5611,0.09300,16.5,18.0,19.7,21.6,23.7,26.1,28.9
107,118.5,-0.3521,21.7588,0.09331,16.7,18.2,19.9,21.8,23.9,26.4,29.2
108,119.0,-0.3521,21.9568,0.09362,16.8,18.3,20.0,22.0,24.1,26.6,29.5
109,119.5,-0.3521,22.1549,0.09393,16.9,18.5,20.2,22.2,24.4,26.9,29.8
110,120.0,-0.3521,22.3530,0.09424,17.1,18.6,20.4,22.4,24.6,27.2,30.1

In [1]:
len("Berisiko gizi lebih (possible risk of overweight)")

49

In [2]:
18 * 30

540